### ISSUE TITLE
Organization of the folder directories for the mozillaclubs gh-repo.

### ISSUE THREAD

**Issue by ghost** [mozilla/mozillaclubs#4]
Was thinking the repository could use some basic structure so it matches other repositories.  
Also, the [read me](README.md) file could state the purpose of the repo, for instance,
### "This repository was made to house resources, images, ect.."  

Maybe create a project for it or a milestone?

**Comment by Carotejada** [comment]
@KipOmaha thank you! I'm actually working on that right now, so all your ideas to improve the Repo  are more than welcome!!!  

I'm completing the README, LICENSE AND CONTRIBUTING files for the Design Resources folder.

**Comment by ghost** [comment]
@Carotejada, thanks for the invite. I'd be glad to help in anyway I can.

**Comment by ghost** [comment]
@Carotejada, mind if I make a pull request for a CONTRIBUTING.md file for the main directory?  

I was thinking of writing it out on google docs first though and inviting people. How does that sound?

**Comment by Carotejada** [comment]
@KipOmaha I think that's a goo idea. Please do!

**Comment by ghost** [comment]
thanks for the go ahead. I didn't mean to push it already I didn't know I had the privileges when I put it to the repo already.  I just wanted to put it as a pull request than it already pushed it...

<-- newbie mistake sorry. it won't happen again.
